FROM node:20-bullseye

WORKDIR /e2e

COPY package.json playwright.config.ts eslint.config.js ./
COPY tests ./tests

RUN npm install
RUN npx playwright install --with-deps

CMD ["npx", "playwright", "test"]
